<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $countryId = Country::where("code", "BD")->value("id");

        if (! $countryId) {
            return;
        }

        $stateIds = State::where("country_id", $countryId)->pluck("id", "name");

        $citiesByDivision = [
            'Barishal' => [
                ['name' => 'Jhalakathi Sadar', 'local_name' => 'ঝালকাঠি সদর'],
                ['name' => 'Kathalia', 'local_name' => 'কাঠালিয়া'],
                ['name' => 'Nalchity', 'local_name' => 'নলছিটি'],
                ['name' => 'Rajapur', 'local_name' => 'রাজাপুর'],
                ['name' => 'Bauphal', 'local_name' => 'বাউফল'],
                ['name' => 'Patuakhali Sadar', 'local_name' => 'পটুয়াখালী সদর'],
                ['name' => 'Dumki', 'local_name' => 'দুমকি'],
                ['name' => 'Dashmina', 'local_name' => 'দশমিনা'],
                ['name' => 'Kalapara', 'local_name' => 'কলাপাড়া'],
                ['name' => 'Mirzaganj', 'local_name' => 'মির্জাগঞ্জ'],
                ['name' => 'Galachipa', 'local_name' => 'গলাচিপা'],
                ['name' => 'Rangabali', 'local_name' => 'রাঙ্গাবালী'],
                ['name' => 'Pirojpur Sadar', 'local_name' => 'পিরোজপুর সদর'],
                ['name' => 'Nazirpur', 'local_name' => 'নাজিরপুর'],
                ['name' => 'Kawkhali', 'local_name' => 'কাউখালী'],
                ['name' => 'Zianagar', 'local_name' => 'জিয়ানগর'],
                ['name' => 'Bhandaria', 'local_name' => 'ভান্ডারিয়া'],
                ['name' => 'Mathbaria', 'local_name' => 'মঠবাড়ীয়া'],
                ['name' => 'Nesarabad', 'local_name' => 'নেছারাবাদ'],
                ['name' => 'Barisal Sadar', 'local_name' => 'বরিশাল সদর'],
                ['name' => 'Bakerganj', 'local_name' => 'বাকেরগঞ্জ'],
                ['name' => 'Babuganj', 'local_name' => 'বাবুগঞ্জ'],
                ['name' => 'Wazirpur', 'local_name' => 'উজিরপুর'],
                ['name' => 'Banaripara', 'local_name' => 'বানারীপাড়া'],
                ['name' => 'Gournadi', 'local_name' => 'গৌরনদী'],
                ['name' => 'Agailjhara', 'local_name' => 'আগৈলঝাড়া'],
                ['name' => 'Mehendiganj', 'local_name' => 'মেহেন্দিগঞ্জ'],
                ['name' => 'Muladi', 'local_name' => 'মুলাদী'],
                ['name' => 'Hizla', 'local_name' => 'হিজলা'],
                ['name' => 'Bhola Sadar', 'local_name' => 'ভোলা সদর'],
                ['name' => 'Borhan Uddin', 'local_name' => 'বোরহান উদ্দিন'],
                ['name' => 'Charfesson', 'local_name' => 'চরফ্যাশন'],
                ['name' => 'Doulatkhan', 'local_name' => 'দৌলতখান'],
                ['name' => 'Monpura', 'local_name' => 'মনপুরা'],
                ['name' => 'Tazumuddin', 'local_name' => 'তজুমদ্দিন'],
                ['name' => 'Lalmohan', 'local_name' => 'লালমোহন'],
                ['name' => 'Amtali', 'local_name' => 'আমতলী'],
                ['name' => 'Barguna Sadar', 'local_name' => 'বরগুনা সদর'],
                ['name' => 'Betagi', 'local_name' => 'বেতাগী'],
                ['name' => 'Bamna', 'local_name' => 'বামনা'],
                ['name' => 'Pathorghata', 'local_name' => 'পাথরঘাটা'],
                ['name' => 'Taltali', 'local_name' => 'তালতলি'],
            ],
            'Chattogram' => [
                ['name' => 'Chattogram Sadar', 'local_name' => 'চট্টগ্রাম সদর'],
                ['name' => 'Debidwar', 'local_name' => 'দেবিদ্বার'],
                ['name' => 'Barura', 'local_name' => 'বরুড়া'],
                ['name' => 'Brahmanpara', 'local_name' => 'ব্রাহ্মণপাড়া'],
                ['name' => 'Chandina', 'local_name' => 'চান্দিনা'],
                ['name' => 'Chauddagram', 'local_name' => 'চৌদ্দগ্রাম'],
                ['name' => 'Daudkandi', 'local_name' => 'দাউদকান্দি'],
                ['name' => 'Homna', 'local_name' => 'হোমনা'],
                ['name' => 'Laksam', 'local_name' => 'লাকসাম'],
                ['name' => 'Muradnagar', 'local_name' => 'মুরাদনগর'],
                ['name' => 'Nangalkot', 'local_name' => 'নাঙ্গলকোট'],
                ['name' => 'Comilla Sadar', 'local_name' => 'কুমিল্লা সদর'],
                ['name' => 'Meghna', 'local_name' => 'মেঘনা'],
                ['name' => 'Monohargonj', 'local_name' => 'মনোহরগঞ্জ'],
                ['name' => 'Sadarsouth', 'local_name' => 'সদর দক্ষিণ'],
                ['name' => 'Titas', 'local_name' => 'তিতাস'],
                ['name' => 'Burichang', 'local_name' => 'বুড়িচং'],
                ['name' => 'Lalmai', 'local_name' => 'লালমাই'],
                ['name' => 'Chhagalnaiya', 'local_name' => 'ছাগলনাইয়া'],
                ['name' => 'Feni Sadar', 'local_name' => 'ফেনী সদর'],
                ['name' => 'Sonagazi', 'local_name' => 'সোনাগাজী'],
                ['name' => 'Fulgazi', 'local_name' => 'ফুলগাজী'],
                ['name' => 'Parshuram', 'local_name' => 'পরশুরাম'],
                ['name' => 'Daganbhuiyan', 'local_name' => 'দাগনভূঞা'],
                ['name' => 'Brahmanbaria Sadar', 'local_name' => 'ব্রাহ্মণবাড়িয়া সদর'],
                ['name' => 'Kasba', 'local_name' => 'কসবা'],
                ['name' => 'Nasirnagar', 'local_name' => 'নাসিরনগর'],
                ['name' => 'Sarail', 'local_name' => 'সরাইল'],
                ['name' => 'Ashuganj', 'local_name' => 'আশুগঞ্জ'],
                ['name' => 'Akhaura', 'local_name' => 'আখাউড়া'],
                ['name' => 'Nabinagar', 'local_name' => 'নবীনগর'],
                ['name' => 'Bancharampur', 'local_name' => 'বাঞ্ছারামপুর'],
                ['name' => 'Bijoynagar', 'local_name' => 'বিজয়নগর'],
                ['name' => 'Rangamati Sadar', 'local_name' => 'রাঙ্গামাটি সদর'],
                ['name' => 'Kaptai', 'local_name' => 'কাপ্তাই'],
                ['name' => 'Kawkhali', 'local_name' => 'কাউখালী'],
                ['name' => 'Baghaichari', 'local_name' => 'বাঘাইছড়ি'],
                ['name' => 'Barkal', 'local_name' => 'বরকল'],
                ['name' => 'Langadu', 'local_name' => 'লংগদু'],
                ['name' => 'Rajasthali', 'local_name' => 'রাজস্থলী'],
                ['name' => 'Belaichari', 'local_name' => 'বিলাইছড়ি'],
                ['name' => 'Juraichari', 'local_name' => 'জুরাছড়ি'],
                ['name' => 'Naniarchar', 'local_name' => 'নানিয়ারচর'],
                ['name' => 'Noakhali Sadar', 'local_name' => 'নোয়াখালী সদর'],
                ['name' => 'Companiganj', 'local_name' => 'কোম্পানীগঞ্জ'],
                ['name' => 'Begumganj', 'local_name' => 'বেগমগঞ্জ'],
                ['name' => 'Hatia', 'local_name' => 'হাতিয়া'],
                ['name' => 'Subarnachar', 'local_name' => 'সুবর্ণচর'],
                ['name' => 'Kabirhat', 'local_name' => 'কবিরহাট'],
                ['name' => 'Senbug', 'local_name' => 'সেনবাগ'],
                ['name' => 'Chatkhil', 'local_name' => 'চাটখিল'],
                ['name' => 'Sonaimori', 'local_name' => 'সোনাইমুড়ী'],
                ['name' => 'Haimchar', 'local_name' => 'হাইমচর'],
                ['name' => 'Kachua', 'local_name' => 'কচুয়া'],
                ['name' => 'Shahrasti', 'local_name' => 'শাহরাস্তি'],
                ['name' => 'Chandpur Sadar', 'local_name' => 'চাঁদপুর সদর'],
                ['name' => 'Matlab South', 'local_name' => 'মতলব দক্ষিণ'],
                ['name' => 'Hajiganj', 'local_name' => 'হাজীগঞ্জ'],
                ['name' => 'Matlab North', 'local_name' => 'মতলব উত্তর'],
                ['name' => 'Faridgonj', 'local_name' => 'ফরিদগঞ্জ'],
                ['name' => 'Lakshmipur Sadar', 'local_name' => 'লক্ষ্মীপুর সদর'],
                ['name' => 'Kamalnagar', 'local_name' => 'কমলনগর'],
                ['name' => 'Raipur', 'local_name' => 'রায়পুর'],
                ['name' => 'Ramgati', 'local_name' => 'রামগতি'],
                ['name' => 'Ramganj', 'local_name' => 'রামগঞ্জ'],
                ['name' => 'Rangunia', 'local_name' => 'রাঙ্গুনিয়া'],
                ['name' => 'Sitakunda', 'local_name' => 'সীতাকুন্ড'],
                ['name' => 'Mirsharai', 'local_name' => 'মীরসরাই'],
                ['name' => 'Patiya', 'local_name' => 'পটিয়া'],
                ['name' => 'Sandwip', 'local_name' => 'সন্দ্বীপ'],
                ['name' => 'Banshkhali', 'local_name' => 'বাঁশখালী'],
                ['name' => 'Boalkhali', 'local_name' => 'বোয়ালখালী'],
                ['name' => 'Anwara', 'local_name' => 'আনোয়ারা'],
                ['name' => 'Chandanaish', 'local_name' => 'চন্দনাইশ'],
                ['name' => 'Satkania', 'local_name' => 'সাতকানিয়া'],
                ['name' => 'Lohagara', 'local_name' => 'লোহাগাড়া'],
                ['name' => 'Hathazari', 'local_name' => 'হাটহাজারী'],
                ['name' => 'Fatikchhari', 'local_name' => 'ফটিকছড়ি'],
                ['name' => 'Raozan', 'local_name' => 'রাউজান'],
                ['name' => 'Karnafuli', 'local_name' => 'কর্ণফুলী'],
                ['name' => 'Coxsbazar Sadar', 'local_name' => 'কক্সবাজার সদর'],
                ['name' => 'Chakaria', 'local_name' => 'চকরিয়া'],
                ['name' => 'Kutubdia', 'local_name' => 'কুতুবদিয়া'],
                ['name' => 'Ukhiya', 'local_name' => 'উখিয়া'],
                ['name' => 'Moheshkhali', 'local_name' => 'মহেশখালী'],
                ['name' => 'Pekua', 'local_name' => 'পেকুয়া'],
                ['name' => 'Ramu', 'local_name' => 'রামু'],
                ['name' => 'Teknaf', 'local_name' => 'টেকনাফ'],
                ['name' => 'Khagrachhari Sadar', 'local_name' => 'খাগড়াছড়ি সদর'],
                ['name' => 'Dighinala', 'local_name' => 'দিঘীনালা'],
                ['name' => 'Panchari', 'local_name' => 'পানছড়ি'],
                ['name' => 'Laxmichhari', 'local_name' => 'লক্ষীছড়ি'],
                ['name' => 'Mohalchari', 'local_name' => 'মহালছড়ি'],
                ['name' => 'Manikchari', 'local_name' => 'মানিকছড়ি'],
                ['name' => 'Ramgarh', 'local_name' => 'রামগড়'],
                ['name' => 'Matiranga', 'local_name' => 'মাটিরাঙ্গা'],
                ['name' => 'Guimara', 'local_name' => 'গুইমারা'],
                ['name' => 'Bandarban Sadar', 'local_name' => 'বান্দরবান সদর'],
                ['name' => 'Alikadam', 'local_name' => 'আলীকদম'],
                ['name' => 'Naikhongchhari', 'local_name' => 'নাইক্ষ্যংছড়ি'],
                ['name' => 'Rowangchhari', 'local_name' => 'রোয়াংছড়ি'],
                ['name' => 'Lama', 'local_name' => 'লামা'],
                ['name' => 'Ruma', 'local_name' => 'রুমা'],
                ['name' => 'Thanchi', 'local_name' => 'থানচি'],
                ['name' => 'Eidgaon', 'local_name' => 'ঈদগাঁও'],
            ],
            'Dhaka' => [
                ['name' => 'Dhaka Metropolitan', 'local_name' => 'ঢাকা সদর'],
                ['name' => 'Belabo', 'local_name' => 'বেলাবো'],
                ['name' => 'Monohardi', 'local_name' => 'মনোহরদী'],
                ['name' => 'Narsingdi Sadar', 'local_name' => 'নরসিংদী সদর'],
                ['name' => 'Palash', 'local_name' => 'পলাশ'],
                ['name' => 'Raipura', 'local_name' => 'রায়পুরা'],
                ['name' => 'Shibpur', 'local_name' => 'শিবপুর'],
                ['name' => 'Kaliganj', 'local_name' => 'কালীগঞ্জ'],
                ['name' => 'Kaliakair', 'local_name' => 'কালিয়াকৈর'],
                ['name' => 'Kapasia', 'local_name' => 'কাপাসিয়া'],
                ['name' => 'Gazipur Sadar', 'local_name' => 'গাজীপুর সদর'],
                ['name' => 'Sreepur', 'local_name' => 'শ্রীপুর'],
                ['name' => 'Shariatpur Sadar', 'local_name' => 'শরিয়তপুর সদর'],
                ['name' => 'Naria', 'local_name' => 'নড়িয়া'],
                ['name' => 'Zajira', 'local_name' => 'জাজিরা'],
                ['name' => 'Gosairhat', 'local_name' => 'গোসাইরহাট'],
                ['name' => 'Bhedarganj', 'local_name' => 'ভেদরগঞ্জ'],
                ['name' => 'Damudya', 'local_name' => 'ডামুড্যা'],
                ['name' => 'Araihazar', 'local_name' => 'আড়াইহাজার'],
                ['name' => 'Bandar', 'local_name' => 'বন্দর'],
                ['name' => 'Narayanganj Sadar', 'local_name' => 'নারায়নগঞ্জ সদর'],
                ['name' => 'Rupganj', 'local_name' => 'রূপগঞ্জ'],
                ['name' => 'Sonargaon', 'local_name' => 'সোনারগাঁ'],
                ['name' => 'Basail', 'local_name' => 'বাসাইল'],
                ['name' => 'Bhuapur', 'local_name' => 'ভুয়াপুর'],
                ['name' => 'Delduar', 'local_name' => 'দেলদুয়ার'],
                ['name' => 'Ghatail', 'local_name' => 'ঘাটাইল'],
                ['name' => 'Gopalpur', 'local_name' => 'গোপালপুর'],
                ['name' => 'Madhupur', 'local_name' => 'মধুপুর'],
                ['name' => 'Mirzapur', 'local_name' => 'মির্জাপুর'],
                ['name' => 'Nagarpur', 'local_name' => 'নাগরপুর'],
                ['name' => 'Sakhipur', 'local_name' => 'সখিপুর'],
                ['name' => 'Tangail Sadar', 'local_name' => 'টাঙ্গাইল সদর'],
                ['name' => 'Kalihati', 'local_name' => 'কালিহাতী'],
                ['name' => 'Dhanbari', 'local_name' => 'ধনবাড়ী'],
                ['name' => 'Itna', 'local_name' => 'ইটনা'],
                ['name' => 'Katiadi', 'local_name' => 'কটিয়াদী'],
                ['name' => 'Bhairab', 'local_name' => 'ভৈরব'],
                ['name' => 'Tarail', 'local_name' => 'তাড়াইল'],
                ['name' => 'Hossainpur', 'local_name' => 'হোসেনপুর'],
                ['name' => 'Pakundia', 'local_name' => 'পাকুন্দিয়া'],
                ['name' => 'Kuliarchar', 'local_name' => 'কুলিয়ারচর'],
                ['name' => 'Kishoreganj Sadar', 'local_name' => 'কিশোরগঞ্জ সদর'],
                ['name' => 'Karimgonj', 'local_name' => 'করিমগঞ্জ'],
                ['name' => 'Bajitpur', 'local_name' => 'বাজিতপুর'],
                ['name' => 'Austagram', 'local_name' => 'অষ্টগ্রাম'],
                ['name' => 'Mithamoin', 'local_name' => 'মিঠামইন'],
                ['name' => 'Nikli', 'local_name' => 'নিকলী'],
                ['name' => 'Harirampur', 'local_name' => 'হরিরামপুর'],
                ['name' => 'Saturia', 'local_name' => 'সাটুরিয়া'],
                ['name' => 'Manikganj Sadar', 'local_name' => 'মানিকগঞ্জ সদর'],
                ['name' => 'Gior', 'local_name' => 'ঘিওর'],
                ['name' => 'Shibaloy', 'local_name' => 'শিবালয়'],
                ['name' => 'Doulatpur', 'local_name' => 'দৌলতপুর'],
                ['name' => 'Singiar', 'local_name' => 'সিংগাইর'],
                ['name' => 'Savar', 'local_name' => 'সাভার'],
                ['name' => 'Dhamrai', 'local_name' => 'ধামরাই'],
                ['name' => 'Keraniganj', 'local_name' => 'কেরাণীগঞ্জ'],
                ['name' => 'Nawabganj', 'local_name' => 'নবাবগঞ্জ'],
                ['name' => 'Dohar', 'local_name' => 'দোহার'],
                ['name' => 'Munshiganj Sadar', 'local_name' => 'মুন্সিগঞ্জ সদর'],
                ['name' => 'Sreenagar', 'local_name' => 'শ্রীনগর'],
                ['name' => 'Sirajdikhan', 'local_name' => 'সিরাজদিখান'],
                ['name' => 'Louhajanj', 'local_name' => 'লৌহজং'],
                ['name' => 'Gajaria', 'local_name' => 'গজারিয়া'],
                ['name' => 'Tongibari', 'local_name' => 'টংগীবাড়ি'],
                ['name' => 'Rajbari Sadar', 'local_name' => 'রাজবাড়ী সদর'],
                ['name' => 'Goalanda', 'local_name' => 'গোয়ালন্দ'],
                ['name' => 'Pangsa', 'local_name' => 'পাংশা'],
                ['name' => 'Baliakandi', 'local_name' => 'বালিয়াকান্দি'],
                ['name' => 'Kalukhali', 'local_name' => 'কালুখালী'],
                ['name' => 'Madaripur Sadar', 'local_name' => 'মাদারীপুর সদর'],
                ['name' => 'Shibchar', 'local_name' => 'শিবচর'],
                ['name' => 'Kalkini', 'local_name' => 'কালকিনি'],
                ['name' => 'Rajoir', 'local_name' => 'রাজৈর'],
                ['name' => 'Gopalganj Sadar', 'local_name' => 'গোপালগঞ্জ সদর'],
                ['name' => 'Kashiani', 'local_name' => 'কাশিয়ানী'],
                ['name' => 'Tungipara', 'local_name' => 'টুংগীপাড়া'],
                ['name' => 'Kotalipara', 'local_name' => 'কোটালীপাড়া'],
                ['name' => 'Muksudpur', 'local_name' => 'মুকসুদপুর'],
                ['name' => 'Faridpur Sadar', 'local_name' => 'ফরিদপুর সদর'],
                ['name' => 'Alfadanga', 'local_name' => 'আলফাডাঙ্গা'],
                ['name' => 'Boalmari', 'local_name' => 'বোয়ালমারী'],
                ['name' => 'Sadarpur', 'local_name' => 'সদরপুর'],
                ['name' => 'Nagarkanda', 'local_name' => 'নগরকান্দা'],
                ['name' => 'Bhanga', 'local_name' => 'ভাঙ্গা'],
                ['name' => 'Charbhadrasan', 'local_name' => 'চরভদ্রাসন'],
                ['name' => 'Madhukhali', 'local_name' => 'মধুখালী'],
                ['name' => 'Saltha', 'local_name' => 'সালথা'],
                ['name' => 'Dasar', 'local_name' => 'ডাসার'],
            ],
            'Khulna' => [
                ['name' => 'Khulna Sadar', 'local_name' => 'খুলনা সদর'],
                ['name' => 'Manirampur', 'local_name' => 'মণিরামপুর'],
                ['name' => 'Abhaynagar', 'local_name' => 'অভয়নগর'],
                ['name' => 'Bagherpara', 'local_name' => 'বাঘারপাড়া'],
                ['name' => 'Chougachha', 'local_name' => 'চৌগাছা'],
                ['name' => 'Jhikargacha', 'local_name' => 'ঝিকরগাছা'],
                ['name' => 'Keshabpur', 'local_name' => 'কেশবপুর'],
                ['name' => 'Jessore Sadar', 'local_name' => 'যশোর সদর'],
                ['name' => 'Sharsha', 'local_name' => 'শার্শা'],
                ['name' => 'Assasuni', 'local_name' => 'আশাশুনি'],
                ['name' => 'Debhata', 'local_name' => 'দেবহাটা'],
                ['name' => 'Kalaroa', 'local_name' => 'কলারোয়া'],
                ['name' => 'Satkhira Sadar', 'local_name' => 'সাতক্ষীরা সদর'],
                ['name' => 'Shyamnagar', 'local_name' => 'শ্যামনগর'],
                ['name' => 'Tala', 'local_name' => 'তালা'],
                ['name' => 'Kaliganj (Satkhira)', 'local_name' => 'কালিগঞ্জ'],
                ['name' => 'Mujibnagar', 'local_name' => 'মুজিবনগর'],
                ['name' => 'Meherpur Sadar', 'local_name' => 'মেহেরপুর সদর'],
                ['name' => 'Gangni', 'local_name' => 'গাংনী'],
                ['name' => 'Narail Sadar', 'local_name' => 'নড়াইল সদর'],
                ['name' => 'Lohagara', 'local_name' => 'লোহাগড়া'],
                ['name' => 'Kalia', 'local_name' => 'কালিয়া'],
                ['name' => 'Chuadanga Sadar', 'local_name' => 'চুয়াডাঙ্গা সদর'],
                ['name' => 'Alamdanga', 'local_name' => 'আলমডাঙ্গা'],
                ['name' => 'Damurhuda', 'local_name' => 'দামুড়হুদা'],
                ['name' => 'Jibannagar', 'local_name' => 'জীবননগর'],
                ['name' => 'Kushtia Sadar', 'local_name' => 'কুষ্টিয়া সদর'],
                ['name' => 'Kumarkhali', 'local_name' => 'কুমারখালী'],
                ['name' => 'Khoksa', 'local_name' => 'খোকসা'],
                ['name' => 'Mirpur', 'local_name' => 'মিরপুর'],
                ['name' => 'Daulatpur', 'local_name' => 'দৌলতপুর'],
                ['name' => 'Bheramara', 'local_name' => 'ভেড়ামারা'],
                ['name' => 'Shalikha', 'local_name' => 'শালিখা'],
                ['name' => 'Sreepur', 'local_name' => 'শ্রীপুর'],
                ['name' => 'Magura Sadar', 'local_name' => 'মাগুরা সদর'],
                ['name' => 'Mohammadpur', 'local_name' => 'মহম্মদপুর'],
                ['name' => 'Paikgasa', 'local_name' => 'পাইকগাছা'],
                ['name' => 'Fultola', 'local_name' => 'ফুলতলা'],
                ['name' => 'Digholia', 'local_name' => 'দিঘলিয়া'],
                ['name' => 'Rupsha', 'local_name' => 'রূপসা'],
                ['name' => 'Terokhada', 'local_name' => 'তেরখাদা'],
                ['name' => 'Dumuria', 'local_name' => 'ডুমুরিয়া'],
                ['name' => 'Botiaghata', 'local_name' => 'বটিয়াঘাটা'],
                ['name' => 'Dakop', 'local_name' => 'দাকোপ'],
                ['name' => 'Koyra', 'local_name' => 'কয়রা'],
                ['name' => 'Fakirhat', 'local_name' => 'ফকিরহাট'],
                ['name' => 'Bagerhat Sadar', 'local_name' => 'বাগেরহাট সদর'],
                ['name' => 'Mollahat', 'local_name' => 'মোল্লাহাট'],
                ['name' => 'Sarankhola', 'local_name' => 'শরণখোলা'],
                ['name' => 'Rampal', 'local_name' => 'রামপাল'],
                ['name' => 'Morrelganj', 'local_name' => 'মোড়েলগঞ্জ'],
                ['name' => 'Kachua', 'local_name' => 'কচুয়া'],
                ['name' => 'Mongla', 'local_name' => 'মোংলা'],
                ['name' => 'Chitalmari', 'local_name' => 'চিতলমারী'],
                ['name' => 'Jhenaidah Sadar', 'local_name' => 'ঝিনাইদহ সদর'],
                ['name' => 'Shailkupa', 'local_name' => 'শৈলকুপা'],
                ['name' => 'Harinakundu', 'local_name' => 'হরিণাকুন্ডু'],
                ['name' => 'Kaliganj (Jhenaidah)', 'local_name' => 'কালীগঞ্জ'],
                ['name' => 'Kotchandpur', 'local_name' => 'কোটচাঁদপুর'],
                ['name' => 'Moheshpur', 'local_name' => 'মহেশপুর'],
            ],
            'Mymensingh' => [
                ['name' => 'Sherpur Sadar', 'local_name' => 'শেরপুর সদর'],
                ['name' => 'Nalitabari', 'local_name' => 'নালিতাবাড়ী'],
                ['name' => 'Sreebordi', 'local_name' => 'শ্রীবরদী'],
                ['name' => 'Nokla', 'local_name' => 'নকলা'],
                ['name' => 'Jhenaigati', 'local_name' => 'ঝিনাইগাতী'],
                ['name' => 'Fulbaria', 'local_name' => 'ফুলবাড়ীয়া'],
                ['name' => 'Trishal', 'local_name' => 'ত্রিশাল'],
                ['name' => 'Bhaluka', 'local_name' => 'ভালুকা'],
                ['name' => 'Muktagacha', 'local_name' => 'মুক্তাগাছা'],
                ['name' => 'Mymensingh Sadar', 'local_name' => 'ময়মনসিংহ সদর'],
                ['name' => 'Dhobaura', 'local_name' => 'ধোবাউড়া'],
                ['name' => 'Phulpur', 'local_name' => 'ফুলপুর'],
                ['name' => 'Haluaghat', 'local_name' => 'হালুয়াঘাট'],
                ['name' => 'Gouripur', 'local_name' => 'গৌরীপুর'],
                ['name' => 'Gafargaon', 'local_name' => 'গফরগাঁও'],
                ['name' => 'Iswarganj', 'local_name' => 'ঈশ্বরগঞ্জ'],
                ['name' => 'Nandail', 'local_name' => 'নান্দাইল'],
                ['name' => 'Tarakanda', 'local_name' => 'তারাকান্দা'],
                ['name' => 'Jamalpur Sadar', 'local_name' => 'জামালপুর সদর'],
                ['name' => 'Melandah', 'local_name' => 'মেলান্দহ'],
                ['name' => 'Islampur', 'local_name' => 'ইসলামপুর'],
                ['name' => 'Dewangonj', 'local_name' => 'দেওয়ানগঞ্জ'],
                ['name' => 'Sarishabari', 'local_name' => 'সরিষাবাড়ী'],
                ['name' => 'Madarganj', 'local_name' => 'মাদারগঞ্জ'],
                ['name' => 'Bokshiganj', 'local_name' => 'বকশীগঞ্জ'],
                ['name' => 'Barhatta', 'local_name' => 'বারহাট্টা'],
                ['name' => 'Durgapur', 'local_name' => 'দুর্গাপুর'],
                ['name' => 'Kendua', 'local_name' => 'কেন্দুয়া'],
                ['name' => 'Atpara', 'local_name' => 'আটপাড়া'],
                ['name' => 'Madan', 'local_name' => 'মদন'],
                ['name' => 'Khaliajuri', 'local_name' => 'খালিয়াজুরী'],
                ['name' => 'Kalmakanda', 'local_name' => 'কলমাকান্দা'],
                ['name' => 'Mohongonj', 'local_name' => 'মোহনগঞ্জ'],
                ['name' => 'Purbadhala', 'local_name' => 'পূর্বধলা'],
                ['name' => 'Netrokona Sadar', 'local_name' => 'নেত্রকোণা সদর'],
            ],
            'Rajshahi' => [
                ['name' => 'Rajshahi Sadar', 'local_name' => 'রাজশাহী সদর'],
                ['name' => 'Belkuchi', 'local_name' => 'বেলকুচি'],
                ['name' => 'Chauhali', 'local_name' => 'চৌহালি'],
                ['name' => 'Kamarkhand', 'local_name' => 'কামারখন্দ'],
                ['name' => 'Kazipur', 'local_name' => 'কাজীপুর'],
                ['name' => 'Raigonj', 'local_name' => 'রায়গঞ্জ'],
                ['name' => 'Shahjadpur', 'local_name' => 'শাহজাদপুর'],
                ['name' => 'Sirajganj Sadar', 'local_name' => 'সিরাজগঞ্জ সদর'],
                ['name' => 'Tarash', 'local_name' => 'তাড়াশ'],
                ['name' => 'Ullapara', 'local_name' => 'উল্লাপাড়া'],
                ['name' => 'Sujanagar', 'local_name' => 'সুজানগর'],
                ['name' => 'Ishurdi', 'local_name' => 'ঈশ্বরদী'],
                ['name' => 'Bhangura', 'local_name' => 'ভাঙ্গুড়া'],
                ['name' => 'Pabna Sadar', 'local_name' => 'পাবনা সদর'],
                ['name' => 'Bera', 'local_name' => 'বেড়া'],
                ['name' => 'Atghoria', 'local_name' => 'আটঘরিয়া'],
                ['name' => 'Chatmohar', 'local_name' => 'চাটমোহর'],
                ['name' => 'Santhia', 'local_name' => 'সাঁথিয়া'],
                ['name' => 'Faridpur', 'local_name' => 'ফরিদপুর'],
                ['name' => 'Kahaloo', 'local_name' => 'কাহালু'],
                ['name' => 'Bogra Sadar', 'local_name' => 'বগুড়া সদর'],
                ['name' => 'Shariakandi', 'local_name' => 'সারিয়াকান্দি'],
                ['name' => 'Shajahanpur', 'local_name' => 'শাজাহানপুর'],
                ['name' => 'Dupchanchia', 'local_name' => 'দুপচাচিঁয়া'],
                ['name' => 'Adamdighi', 'local_name' => 'আদমদিঘি'],
                ['name' => 'Nondigram', 'local_name' => 'নন্দিগ্রাম'],
                ['name' => 'Sonatala', 'local_name' => 'সোনাতলা'],
                ['name' => 'Dhunot', 'local_name' => 'ধুনট'],
                ['name' => 'Gabtali', 'local_name' => 'গাবতলী'],
                ['name' => 'Sherpur', 'local_name' => 'শেরপুর'],
                ['name' => 'Shibganj (Bogura)', 'local_name' => 'শিবগঞ্জ'],
                ['name' => 'Paba', 'local_name' => 'পবা'],
                ['name' => 'Durgapur', 'local_name' => 'দুর্গাপুর'],
                ['name' => 'Mohonpur', 'local_name' => 'মোহনপুর'],
                ['name' => 'Charghat', 'local_name' => 'চারঘাট'],
                ['name' => 'Puthia', 'local_name' => 'পুঠিয়া'],
                ['name' => 'Bagha', 'local_name' => 'বাঘা'],
                ['name' => 'Godagari', 'local_name' => 'গোদাগাড়ী'],
                ['name' => 'Tanore', 'local_name' => 'তানোর'],
                ['name' => 'Bagmara', 'local_name' => 'বাগমারা'],
                ['name' => 'Natore Sadar', 'local_name' => 'নাটোর সদর'],
                ['name' => 'Singra', 'local_name' => 'সিংড়া'],
                ['name' => 'Baraigram', 'local_name' => 'বড়াইগ্রাম'],
                ['name' => 'Bagatipara', 'local_name' => 'বাগাতিপাড়া'],
                ['name' => 'Lalpur', 'local_name' => 'লালপুর'],
                ['name' => 'Gurudaspur', 'local_name' => 'গুরুদাসপুর'],
                ['name' => 'Naldanga', 'local_name' => 'নলডাঙ্গা'],
                ['name' => 'Akkelpur', 'local_name' => 'আক্কেলপুর'],
                ['name' => 'Kalai', 'local_name' => 'কালাই'],
                ['name' => 'Khetlal', 'local_name' => 'ক্ষেতলাল'],
                ['name' => 'Panchbibi', 'local_name' => 'পাঁচবিবি'],
                ['name' => 'Joypurhat Sadar', 'local_name' => 'জয়পুরহাট সদর'],
                ['name' => 'Chapainawabganj Sadar', 'local_name' => 'চাঁপাইনবাবগঞ্জ সদর'],
                ['name' => 'Gomostapur', 'local_name' => 'গোমস্তাপুর'],
                ['name' => 'Nachol', 'local_name' => 'নাচোল'],
                ['name' => 'Bholahat', 'local_name' => 'ভোলাহাট'],
                ['name' => 'Shibganj (Chapainawabganj)', 'local_name' => 'শিবগঞ্জ'],
                ['name' => 'Mohadevpur', 'local_name' => 'মহাদেবপুর'],
                ['name' => 'Badalgachi', 'local_name' => 'বদলগাছী'],
                ['name' => 'Patnitala', 'local_name' => 'পত্নিতলা'],
                ['name' => 'Dhamoirhat', 'local_name' => 'ধামইরহাট'],
                ['name' => 'Niamatpur', 'local_name' => 'নিয়ামতপুর'],
                ['name' => 'Manda', 'local_name' => 'মান্দা'],
                ['name' => 'Atrai', 'local_name' => 'আত্রাই'],
                ['name' => 'Raninagar', 'local_name' => 'রাণীনগর'],
                ['name' => 'Naogaon Sadar', 'local_name' => 'নওগাঁ সদর'],
                ['name' => 'Porsha', 'local_name' => 'পোরশা'],
                ['name' => 'Sapahar', 'local_name' => 'সাপাহার'],
            ],
            'Rangpur' => [
                ['name' => 'Panchagarh Sadar', 'local_name' => 'পঞ্চগড় সদর'],
                ['name' => 'Debiganj', 'local_name' => 'দেবীগঞ্জ'],
                ['name' => 'Boda', 'local_name' => 'বোদা'],
                ['name' => 'Atwari', 'local_name' => 'আটোয়ারী'],
                ['name' => 'Tetulia', 'local_name' => 'তেতুলিয়া'],
                ['name' => 'Nawabganj', 'local_name' => 'নবাবগঞ্জ'],
                ['name' => 'Birganj', 'local_name' => 'বীরগঞ্জ'],
                ['name' => 'Ghoraghat', 'local_name' => 'ঘোড়াঘাট'],
                ['name' => 'Birampur', 'local_name' => 'বিরামপুর'],
                ['name' => 'Parbatipur', 'local_name' => 'পার্বতীপুর'],
                ['name' => 'Bochaganj', 'local_name' => 'বোচাগঞ্জ'],
                ['name' => 'Kaharol', 'local_name' => 'কাহারোল'],
                ['name' => 'Fulbari', 'local_name' => 'ফুলবাড়ী'],
                ['name' => 'Dinajpur Sadar', 'local_name' => 'দিনাজপুর সদর'],
                ['name' => 'Hakimpur', 'local_name' => 'হাকিমপুর'],
                ['name' => 'Khansama', 'local_name' => 'খানসামা'],
                ['name' => 'Birol', 'local_name' => 'বিরল'],
                ['name' => 'Chirirbandar', 'local_name' => 'চিরিরবন্দর'],
                ['name' => 'Lalmonirhat Sadar', 'local_name' => 'লালমনিরহাট সদর'],
                ['name' => 'Kaliganj', 'local_name' => 'কালীগঞ্জ'],
                ['name' => 'Hatibandha', 'local_name' => 'হাতীবান্ধা'],
                ['name' => 'Patgram', 'local_name' => 'পাটগ্রাম'],
                ['name' => 'Aditmari', 'local_name' => 'আদিতমারী'],
                ['name' => 'Syedpur', 'local_name' => 'সৈয়দপুর'],
                ['name' => 'Domar', 'local_name' => 'ডোমার'],
                ['name' => 'Dimla', 'local_name' => 'ডিমলা'],
                ['name' => 'Jaldhaka', 'local_name' => 'জলঢাকা'],
                ['name' => 'Kishorganj', 'local_name' => 'কিশোরগঞ্জ'],
                ['name' => 'Nilphamari Sadar', 'local_name' => 'নীলফামারী সদর'],
                ['name' => 'Sadullapur', 'local_name' => 'সাদুল্লাপুর'],
                ['name' => 'Gaibandha Sadar', 'local_name' => 'গাইবান্ধা সদর'],
                ['name' => 'Palashbari', 'local_name' => 'পলাশবাড়ী'],
                ['name' => 'Saghata', 'local_name' => 'সাঘাটা'],
                ['name' => 'Gobindaganj', 'local_name' => 'গোবিন্দগঞ্জ'],
                ['name' => 'Sundarganj', 'local_name' => 'সুন্দরগঞ্জ'],
                ['name' => 'Phulchari', 'local_name' => 'ফুলছড়ি'],
                ['name' => 'Thakurgaon Sadar', 'local_name' => 'ঠাকুরগাঁও সদর'],
                ['name' => 'Pirganj', 'local_name' => 'পীরগঞ্জ'],
                ['name' => 'Ranisankail', 'local_name' => 'রাণীশংকৈল'],
                ['name' => 'Haripur', 'local_name' => 'হরিপুর'],
                ['name' => 'Baliadangi', 'local_name' => 'বালিয়াডাঙ্গী'],
                ['name' => 'Rangpur Sadar', 'local_name' => 'রংপুর সদর'],
                ['name' => 'Gangachara', 'local_name' => 'গংগাচড়া'],
                ['name' => 'Taragonj', 'local_name' => 'তারাগঞ্জ'],
                ['name' => 'Badargonj', 'local_name' => 'বদরগঞ্জ'],
                ['name' => 'Mithapukur', 'local_name' => 'মিঠাপুকুর'],
                ['name' => 'Pirgonj', 'local_name' => 'পীরগঞ্জ'],
                ['name' => 'Kaunia', 'local_name' => 'কাউনিয়া'],
                ['name' => 'Pirgacha', 'local_name' => 'পীরগাছা'],
                ['name' => 'Kurigram Sadar', 'local_name' => 'কুড়িগ্রাম সদর'],
                ['name' => 'Nageshwari', 'local_name' => 'নাগেশ্বরী'],
                ['name' => 'Bhurungamari', 'local_name' => 'ভুরুঙ্গামারী'],
                ['name' => 'Phulbari', 'local_name' => 'ফুলবাড়ী'],
                ['name' => 'Rajarhat', 'local_name' => 'রাজারহাট'],
                ['name' => 'Ulipur', 'local_name' => 'উলিপুর'],
                ['name' => 'Chilmari', 'local_name' => 'চিলমারী'],
                ['name' => 'Rowmari', 'local_name' => 'রৌমারী'],
                ['name' => 'Charrajibpur', 'local_name' => 'চর রাজিবপুর'],
            ],
            'Sylhet' => [
                ['name' => 'Balaganj', 'local_name' => 'বালাগঞ্জ'],
                ['name' => 'Beanibazar', 'local_name' => 'বিয়ানীবাজার'],
                ['name' => 'Bishwanath', 'local_name' => 'বিশ্বনাথ'],
                ['name' => 'Companiganj', 'local_name' => 'কোম্পানীগঞ্জ'],
                ['name' => 'Fenchuganj', 'local_name' => 'ফেঞ্চুগঞ্জ'],
                ['name' => 'Golapganj', 'local_name' => 'গোলাপগঞ্জ'],
                ['name' => 'Gowainghat', 'local_name' => 'গোয়াইনঘাট'],
                ['name' => 'Jaintiapur', 'local_name' => 'জৈন্তাপুর'],
                ['name' => 'Kanaighat', 'local_name' => 'কানাইঘাট'],
                ['name' => 'Sylhet Sadar', 'local_name' => 'সিলেট সদর'],
                ['name' => 'Zakiganj', 'local_name' => 'জকিগঞ্জ'],
                ['name' => 'Dakshinsurma', 'local_name' => 'দক্ষিণ সুরমা'],
                ['name' => 'Osmaninagar', 'local_name' => 'ওসমানী নগর'],
                ['name' => 'Barlekha', 'local_name' => 'বড়লেখা'],
                ['name' => 'Kamolganj', 'local_name' => 'কমলগঞ্জ'],
                ['name' => 'Kulaura', 'local_name' => 'কুলাউড়া'],
                ['name' => 'Moulvibazar Sadar', 'local_name' => 'মৌলভীবাজার সদর'],
                ['name' => 'Rajnagar', 'local_name' => 'রাজনগর'],
                ['name' => 'Sreemangal', 'local_name' => 'শ্রীমঙ্গল'],
                ['name' => 'Juri', 'local_name' => 'জুড়ী'],
                ['name' => 'Nabiganj', 'local_name' => 'নবীগঞ্জ'],
                ['name' => 'Bahubal', 'local_name' => 'বাহুবল'],
                ['name' => 'Ajmiriganj', 'local_name' => 'আজমিরীগঞ্জ'],
                ['name' => 'Baniachong', 'local_name' => 'বানিয়াচং'],
                ['name' => 'Lakhai', 'local_name' => 'লাখাই'],
                ['name' => 'Chunarughat', 'local_name' => 'চুনারুঘাট'],
                ['name' => 'Habiganj Sadar', 'local_name' => 'হবিগঞ্জ সদর'],
                ['name' => 'Madhabpur', 'local_name' => 'মাধবপুর'],
                ['name' => 'Sunamganj Sadar', 'local_name' => 'সুনামগঞ্জ সদর'],
                ['name' => 'South Sunamganj', 'local_name' => 'দক্ষিণ সুনামগঞ্জ'],
                ['name' => 'Bishwambarpur', 'local_name' => 'বিশ্বম্ভরপুর'],
                ['name' => 'Chhatak', 'local_name' => 'ছাতক'],
                ['name' => 'Jagannathpur', 'local_name' => 'জগন্নাথপুর'],
                ['name' => 'Dowarabazar', 'local_name' => 'দোয়ারাবাজার'],
                ['name' => 'Tahirpur', 'local_name' => 'তাহিরপুর'],
                ['name' => 'Dharmapasha', 'local_name' => 'ধর্মপাশা'],
                ['name' => 'Jamalganj', 'local_name' => 'জামালগঞ্জ'],
                ['name' => 'Shalla', 'local_name' => 'শাল্লা'],
                ['name' => 'Derai', 'local_name' => 'দিরাই'],
                ['name' => 'Madhyanagar', 'local_name' => 'মধ্যনগর'],
            ],

        ];

        foreach ($citiesByDivision as $divisionName => $cities) {
            $stateId = $stateIds[$divisionName] ?? null;

            if (! $stateId) {
                continue;
            }

            foreach ($cities as $index => $city) {
                DB::table("cities")->updateOrInsert(
                    ["state_id" => $stateId, "name" => $city["name"]],
                    [
                        "country_id" => $countryId,
                        "state_id"   => $stateId,
                        "name"       => $city["name"],
                        "local_name" => $city["local_name"],
                        "code"       => Str::slug($city["name"]),
                        "is_active"  => true,
                        "sort_order" => $index + 1,
                        "updated_at" => now(),
                        "created_at" => now(),
                    ]
                );
            }
        }
    }
}
