Table users {
  id bigint [pk, increment]
  name varchar
  email varchar [unique, not null]
  email_verified_at timestamp [null]
  phone_verified_at timestamp [null]
  phone varchar [null]
  country_code varchar [null]
  address varchar [null]
  bio text [null]
  gender varchar [null]
  password varchar [not null]
  two_factor_secret text [null]
  two_factor_recovery_codes text [null]
  two_factor_confirmed_at timestamp [null]
  otp varchar [null]
  otp_expires_at timestamp [null]
  status varchar [default: 'active']
  remember_token varchar [null]
  current_team_id bigint [null]
  avatar_id bigint [null]
  cover_photo_id bigint [null]
  created_at timestamp [null]
  updated_at timestamp [null]
  deleted_at timestamp [null]
}
