<?php

namespace App\Support\EcomxFashion;

/**
 * File-backed (no DB) registry of per-page section active/order state.
 * Storage: storage/app/private/themes/{active theme}/page-sections.json — see
 * ActiveTheme::storagePath(). The theme's schema (which pages exist and which
 * sections each declares) lives in config('{theme}.pages'); this file only
 * holds the admin's runtime toggles/order, so it's git-ignored and never
 * touched by a deploy. It's generated by syncAllPages() ("Sync all pages" in
 * the admin); until then forPage() falls back to the config defaults.
 *
 * Reads/writes use flock() so concurrent admin requests can't interleave and
 * corrupt the file; writes go to a temp file first and are renamed into place
 * (atomic on the same filesystem) so a crash mid-write never leaves a
 * half-written JSON file behind.
 */
class PageSectionRegistry
{
    protected static function path(): string
    {
        return ActiveTheme::storagePath('page-sections.json');
    }

    protected static function read(): array
    {
        $path = static::path();

        if (! file_exists($path)) {
            return [];
        }

        $handle = fopen($path, 'r');
        if ($handle === false) {
            return [];
        }

        try {
            flock($handle, LOCK_SH);
            $contents = stream_get_contents($handle);
        } finally {
            flock($handle, LOCK_UN);
            fclose($handle);
        }

        $data = json_decode($contents, true);

        return is_array($data) ? $data : [];
    }

    protected static function write(array $data): void
    {
        $path = static::path();
        $dir = dirname($path);

        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $tmp = $path . '.' . uniqid('', true) . '.tmp';
        file_put_contents($tmp, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        rename($tmp, $path);
    }

    /** Whether page-sections.json has been generated yet (see syncAllPages()). */
    public static function isGenerated(): bool
    {
        return file_exists(static::path());
    }

    /** Default section list for a page — all its config-declared keys, active, in config order. */
    protected static function defaultsFromConfig(string $page): array
    {
        $configuredKeys = PageRegistry::sectionKeysForPage($page);

        return array_map(fn (int $order, string $key) => [
            'key' => $key,
            'active' => true,
            'order' => $order,
        ], array_keys($configuredKeys), $configuredKeys);
    }

    /**
     * All sections for a page, ordered, each as ['key'=>, 'active'=>, 'order'=>].
     * Falls back to defaultsFromConfig() when this page has never been saved.
     */
    public static function forPage(string $page): array
    {
        $data = static::read();
        $sections = $data[$page] ?? static::defaultsFromConfig($page);

        // Config is the schema: hide saved sections no longer declared for this page.
        $configuredKeys = PageRegistry::sectionKeysForPage($page);
        $sections = array_values(array_filter($sections, fn ($s) => in_array($s['key'], $configuredKeys, true)));

        usort($sections, fn ($a, $b) => ($a['order'] ?? 0) <=> ($b['order'] ?? 0));

        return $sections;
    }

    /** Active section keys for a page, in order — what the frontend renders. */
    public static function activeKeysForPage(string $page): array
    {
        return array_values(array_map(
            fn ($s) => $s['key'],
            array_filter(static::forPage($page), fn ($s) => ! empty($s['active']))
        ));
    }

    public static function pages(): array
    {
        return array_keys(static::read());
    }

    /**
     * Registers every config-declared page and section into page-sections.json
     * in one pass: a page missing from the file is seeded with all its config
     * sections (active, config order); a page already saved gets the config
     * section keys it's missing appended at the end (active) and loses keys
     * no longer declared in config('{theme}.pages'), without clobbering the
     * admin's existing toggles/order for the rest.
     *
     * @return string[] Page keys that were seeded or had sections added/removed.
     */
    public static function syncAllPages(): array
    {
        $data = static::read();
        $seeded = [];

        foreach (PageRegistry::all() as $page => $meta) {
            if (! array_key_exists($page, $data)) {
                $data[$page] = static::defaultsFromConfig($page);
                $seeded[] = $page;

                continue;
            }

            // Already-saved page: drop sections no longer declared in config,
            // and append config sections it's missing (active, at the end) —
            // never touch the remaining toggles/order.
            $configuredKeys = PageRegistry::sectionKeysForPage($page);
            $kept = array_values(array_filter($data[$page], fn ($s) => in_array($s['key'], $configuredKeys, true)));
            $missingKeys = array_values(array_diff($configuredKeys, array_column($kept, 'key')));

            if ($missingKeys === [] && count($kept) === count($data[$page])) {
                continue;
            }

            $nextOrder = $kept === [] ? 0 : max(array_column($kept, 'order')) + 1;

            foreach ($missingKeys as $key) {
                $kept[] = ['key' => $key, 'active' => true, 'order' => $nextOrder++];
            }
            $data[$page] = $kept;
            $seeded[] = $page;
        }

        if ($seeded !== [] || ! static::isGenerated()) {
            static::write($data);
        }

        return $seeded;
    }

    public static function setActive(string $page, string $key, bool $active): void
    {
        $data = static::read();
        $data[$page] = $data[$page] ?? static::defaultsFromConfig($page);

        foreach ($data[$page] as &$section) {
            if ($section['key'] === $key) {
                $section['active'] = $active;
            }
        }
        unset($section);

        static::write($data);
    }

    /** @param string[] $orderedKeys Section keys in their new display order. */
    public static function reorder(string $page, array $orderedKeys): void
    {
        $data = static::read();
        $sections = $data[$page] ?? static::defaultsFromConfig($page);

        foreach ($sections as &$section) {
            $position = array_search($section['key'], $orderedKeys, true);
            if ($position !== false) {
                $section['order'] = $position;
            }
        }
        unset($section);

        $data[$page] = $sections;
        static::write($data);
    }
}
