<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * None of the integrated couriers issue their own webhook signing
     * secret — RedX's docs say to embed "any required credentials" as a
     * query parameter on the callback URL you register, and the others
     * document no signing scheme at all. So the secret is generated by
     * this app itself and appended to the URL shown in Courier > Settings;
     * CourierWebhookController rejects any call whose ?secret= doesn't
     * match this column instead of trusting every request that hits the
     * endpoint (the previous behavior).
     */
    public function up(): void
    {
        Schema::table('couriers', function (Blueprint $table) {
            $table->string('webhook_secret')->nullable()->after('capabilities');
        });
    }

    public function down(): void
    {
        Schema::table('couriers', function (Blueprint $table) {
            $table->dropColumn('webhook_secret');
        });
    }
};
